// <auto-generated />
namespace GalleryMVC_With_Auth.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Comments1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Comments1));
        
        string IMigrationMetadata.Id
        {
            get { return "201510141627328_Comments1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
