// <auto-generated />
namespace GalleryMVC_With_Auth.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tags_Update_Nav5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tags_Update_Nav5));
        
        string IMigrationMetadata.Id
        {
            get { return "201510081933138_Tags_Update_Nav5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
